# {
#   arch      => "x86_64",
#   distri    => "fedora",
#   flavor    => "universal",
#   name      => "",
#   settings  => [
#     { key => "TEST_TARGET", value => "ISO" }
#                ],
#   version   => "*",
# },

# FIXME: name seems unused, do we actually need it?

- name: neon-unstable-bionic
  distri: neon
  version: unstable
  flavor: bionic
  arch: amd64
  settings:
    OPENQA_SERIES: bionic
    TYPE: devedition-gitunstable

- name: neon-unstable-xenial
  distri: neon
  version: unstable
  flavor: xenial
  arch: amd64
  settings:
    OPENQA_SERIES: xenial
    TYPE: devedition-gitunstable
